- name: Install (RehHat/Centos) Apache web server
  apt: pkg=httpd state=latest

- shell: systemctl status httpd
  register: result
  until: result.stdout.find("active (running)") != -1
  retries: 5
  delay: 5
- debug: var=result
