- hosts: webservers
  user: root
  become: yes
  become_user: root
  gather_facts: no

  tasks:
  - name: start time log
    raw: /usr/bin/date
    register: starttime
  - debug: var=starttime

  - name: install httpd
    yum: pkg=httpd state=latest
    notify: start httpd

  - name: verify that the webs service is running
    command: systemctl status httpd
    register: result
    ignore_errors: yes
  - debug: var=result

  - name: install client software telnet
    yum: pkg=telnet state=latest

  - name: install lynx
    yum: pkg=lynx state=latest

  - name: log all installed packages
    raw: yum list installed > /tmp/installed.log

  - name: end time log
    raw: /usr/bin/date
    register: endtime
  - debug: var=endtime

  handlers:
  - name: start httpd
    service: name=httpd state=restarted
