- name: Restart HTTPD
  service: name={{ redhat_apache }} state=restarted
  when: "ansible_os_family == 'RedHat'"
  ignore_errors: yes
- debug: msg="Restart process triggered on RedHat"

- name: Restart Apache2
  service: name={{ debian_apache }} state=restarted
  when: "ansible_os_family == 'Debian'"
  ignore_errors: yes
- debug: msg="Restart process triggered on Debian"
